// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-variants/Cinematic.tsx": () => import("../components/mockups/home-variants/Cinematic.tsx"),
  "./components/mockups/home-variants/Concierge.tsx": () => import("../components/mockups/home-variants/Concierge.tsx"),
  "./components/mockups/home-variants/Editorial.tsx": () => import("../components/mockups/home-variants/Editorial.tsx"),
  "./components/mockups/home-variants/Scrollytell.tsx": () => import("../components/mockups/home-variants/Scrollytell.tsx")
};
